stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - tara_tag
  script:
    - mvn package
  only:
    refs:
      - tara_CICD
    changes:
      - pom.xml
      - src/**/*

maven-test:
  stage: maventest
  tags:
    - tara_tag
  script:
    - mvn test
  only:
    refs:
      - tara_CICD
    changes:
      - pom.xml
      - src/**/*
