stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - tara_tag      # Ensure this matches your runner's tag
  script:
    - cd Backend/tutorials-springboot_unit2_3_filerequests/tutorials-springboot_unit2_3_filerequests/springboot_example
    - mvn package
  only:
    refs:
      - tara_CICD
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - tara_tag      # Ensure this matches your runner's tag
  script:
    - cd Backend/tutorials-springboot_unit2_3_filerequests/tutorials-springboot_unit2_3_filerequests/springboot_example
    - mvn test
  only:
    refs:
      - tara_CICD
    changes:
      - Backend/**/*
