default:
  image: maven:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

stages:
  - test

simple-test:
  stage: test
  tags:
    - tara_tag
  script:
    - echo "Testing pipeline"
  rules:
    - if: '$CI_COMMIT_BRANCH == "tara_CICD" || $CI_PIPELINE_SOURCE == "web"'
      when: always